### ISSUE TITLE
Sanitize strings for line-breaks when TTL'ing

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/prestochango#101]
XML CollectionInventory file might have a line-break in the CDATA content of an element. PC should not pass that into TTL. This seems to happen with the <description> element, which provides a label for the collection.

**Comment by neelsmith** [comment]
This should be systematically coordinated w rng schemas -- some elements don't accept a line break in the schema;  any that do should be sanitized

**Comment by Eumaeus** [comment]
Done.
