### ISSUE TITLE
Label and Canonical Id's… are they properties or not?

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/prestochango#68]
In the XML Collection Inventory, and in our .*sv files, we have one Property that holds the Object's canonical ID, its Cite URN, and one Property that holds a label for the Object.

When we write to RDF, however, those two bits of data don't survive as Properties as such--they don't get `citedata:collection_propName` verbs written. The URN just becomes the subject of all verbs, and the label enters with `rdf:label`. 

I think we should do as we currently do, _but also_ write those into RDF as Properties, like all other properties. It will make things a lot easier.

**Comment by Eumaeus** [comment]
I take it back about the label. We do write that into RDF as a property. But not the Canonical ID property.

**Comment by neelsmith** [comment]
Absolutely they are both properties.  In revised version, they'll be correctly expressed.

**Comment by neelsmith** [comment]
implemented
